### ISSUE TITLE
维基百科支持不友好

### ISSUE THREAD

**Issue by Yumega** [syhyz1990/mactype#28]
很多时候需要刷新页面，才有效果

**Comment by syhyz1990** [comment]
我这里并没有出现这种情况。

**Comment by Yumega** [comment]
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at Object.addPluginStyle (Mactype助手.user.js:156:26)
    at Object.init (Mactype助手.user.js:168:18)
    at Mactype助手.user.js:171:10
    at Mactype助手.user.js:172:3
    at Mactype助手.user.js:173:3
    at Proxy.window.VMin6dp3394w4nkh5t1v (Mactype助手.user.js:173:7)
    at a (injected-web.js:1:20074)
    at v (injected-web.js:1:20181)
    at set (injected-web.js:1:19953)
    at Mactype助手.user.js:1:28

**Comment by Yumega** [comment]
Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at Object.addPluginStyle (userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:160:26)
    at Object.init (userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:172:18)
    at userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:175:10
    at Proxy.tms_3cf44a45_dbf8_4dec_89a9_567c3858070e$ (userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:176:3)
    at it (<anonymous>:14:1074)
    at userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:1:123
    at userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:1:623
    at Object.window.__p__4344081.86771062 (userscript.html?name=Mactype%25E5%258A%25A9%25E6%2589%258B.user.js&id=3cf44a45-dbf8-4dec-89a9-567c3858070e:178:6)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)

**Comment by i1itione** [comment]
我也遇到相同的問題，部分時候（貌似並非 100% 出現）需要 F5 刷新才能讓腳本運作於維基百科頁面。

Chrome v104、暴力猴 2.13.1、MacType 助手 v2.2.2。
